name: Lint Code

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - run: npx eslint .
